### ISSUE TITLE
KeyError in calling _find_no_duplicates

### ISSUE THREAD

**Issue by TechTamer** [neRok00/ancestry-image-downloader#2]
Would you be able to run the script again to see if there is a change in the website breaking the script?

Attempting to login to Ancestry.com...
Traceback (most recent call last):
  File "/Users/username/Downloads/Firefox/ancestry/ancestry-image-downloader/ancestry_image_downloader.py", line 413, in <module>
    run(gedcom=GEDCOM_FILE, username=USERNAME, password=PASSWORD, output_directory=OUTPUT_DIRECTORY)
  File "/Users/username/Downloads/Firefox/ancestry/ancestry-image-downloader/ancestry_image_downloader.py", line 374, in run
    session = start_session(username, password)
  File "/Users/username/Downloads/Firefox/ancestry/ancestry-image-downloader/ancestry_image_downloader.py", line 136, in start_session
    'LOGINNAME=' in response.cookies['VARSESSION']
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='VARSESSION', domain=None, path=None"

**Comment by neRok00** [comment]
Yes, their website changed slightly. I've made the necessary updates in a44ec90, and the script appears to be working. However, I don't have an active subscription, so I can't test if the images are still being downloaded by the script.
